[tool.poetry]
name = "asrhub"
version = "0.1.0"
description = ""
authors = ["metajs <zycode277@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "^4.2.3"
rocketry = "^2.5.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
